services:
  llama_orchestrator:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: llama_orchestrator_vulkan
    network_mode: host
    devices: ["/dev/dri"]
    security_opt: ["seccomp=unconfined"]
    group_add: ["video"]
    volumes:
      - ${LLAMA_MODELS_DIR}:/models
    command: >
      bash -lc "
      llama-server
      --host 0.0.0.0 --port ${LLAMA_ORCH_PORT}
      -m /models/${ORCH_GGUF}
      --no-mmap -ngl 999 --flash-attn on
      "
