services:
  vllm_orchestrator:
    image: docker.io/kyuz0/vllm-therock-gfx1151:latest
    container_name: vllm_orchestrator
    network_mode: host
    devices: ["/dev/kfd", "/dev/dri"]
    security_opt: ["seccomp=unconfined"]
    group_add: ["video", "render"]
    environment:
      - HF_HOME=${HF_HOME}
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ${HF_HOME}:${HF_HOME}
      - ${VLLM_CACHE}:${VLLM_CACHE}
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:${ORCH_PORT}/v1/models || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
    command: >
      vllm serve ${ORCH_MODEL}
      --host 0.0.0.0 --port ${ORCH_PORT}
      --dtype auto
      --gpu-memory-utilization ${ORCH_GPU_UTIL}
      --max-model-len ${ORCH_MAX_LEN}
      --kv-cache-dtype ${ORCH_KV_CACHE_DTYPE:-auto}
      --max-num-seqs ${ORCH_MAX_NUM_SEQS:-256}
      --enable-prefix-caching

  vllm_fast:
    image: docker.io/kyuz0/vllm-therock-gfx1151:latest
    container_name: vllm_fast
    network_mode: host
    devices: ["/dev/kfd", "/dev/dri"]
    security_opt: ["seccomp=unconfined"]
    group_add: ["video", "render"]
    environment:
      - HF_HOME=${HF_HOME}
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ${HF_HOME}:${HF_HOME}
      - ${VLLM_CACHE}:${VLLM_CACHE}
    # Wait for orchestrator to finish loading before starting.
    # On shared-memory GPUs (Strix Halo), concurrent vLLM startup causes
    # memory profiling to see the other instance's allocation, leading to
    # negative KV cache budget and crash.
    depends_on:
      vllm_orchestrator:
        condition: service_healthy
    command: >
      vllm serve ${FAST_MODEL}
      --host 0.0.0.0 --port ${FAST_PORT}
      --dtype auto
      --gpu-memory-utilization ${FAST_GPU_UTIL}
      --max-model-len ${FAST_MAX_LEN}
      --kv-cache-dtype ${FAST_KV_CACHE_DTYPE:-auto}
      --max-num-seqs ${FAST_MAX_NUM_SEQS:-256}
      --enable-prefix-caching
