#!/usr/bin/env bash
set -euo pipefail
docker compose -f compose/vllm.yml --env-file .env down || true
docker compose -f compose/fallback.vulkan-radv.orch.yml --env-file .env down || true
docker compose -f compose/fallback.rocm-6.4.4-rocwmma.orch.yml --env-file .env down || true
